In [1]:
from tensorflow.keras.preprocessing.text import one_hot

In [11]:
## sentences

sent = [

    'the glass of milk',
    'the glass of juice',
    'the cup of tea',
    'I am a good boy',
    'I am a good developer',
    'understand the meaning of words',
    'your videos are good'
]

In [12]:
## define the vocabulary size
voc_size = 10000

In [13]:
## one hot representation
one_hot_repr = [one_hot(words,voc_size)for words in sent]
one_hot_repr

[[266, 8806, 6268, 2244],
 [266, 8806, 6268, 4430],
 [266, 3095, 6268, 7651],
 [1922, 3099, 7072, 9653, 5941],
 [1922, 3099, 7072, 9653, 1609],
 [6814, 266, 9961, 6268, 5451],
 [9571, 7622, 9865, 9653]]

In [14]:
## word embedding representation

from tensorflow.keras.layers import Embedding
from tensorflow.keras.utils import pad_sequences
from tensorflow.keras.models import Sequential


In [15]:
import numpy as np

In [16]:
sent_length = 8
embedded_docs = pad_sequences(one_hot_repr,padding='pre',maxlen=sent_length)
print(embedded_docs)

[[   0    0    0    0  266 8806 6268 2244]
 [   0    0    0    0  266 8806 6268 4430]
 [   0    0    0    0  266 3095 6268 7651]
 [   0    0    0 1922 3099 7072 9653 5941]
 [   0    0    0 1922 3099 7072 9653 1609]
 [   0    0    0 6814  266 9961 6268 5451]
 [   0    0    0    0 9571 7622 9865 9653]]


In [17]:
## feature representation
dim = 10


In [26]:
model = Sequential()
model.add(Embedding(voc_size,dim,input_length=sent_length))
model.compile('adam','mse')

/opt/anaconda3/lib/python3.12/site-packages/keras/src/layers/core/embedding.py:90: UserWarning: Argument `input_length` is deprecated. Just remove it.
  warnings.warn(


In [19]:
model.summary()

Model: "sequential_1"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding_1 (Embedding)         │ ?                      │   0 (unbuilt) │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

In [24]:
model.predict(embedded_docs)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step


array([[[ 0.0340245 , -0.04382233, -0.00749094, -0.04192519,
         -0.04241786, -0.03701735, -0.02274007, -0.01853905,
         -0.01521877,  0.03546393],
        [ 0.0340245 , -0.04382233, -0.00749094, -0.04192519,
         -0.04241786, -0.03701735, -0.02274007, -0.01853905,
         -0.01521877,  0.03546393],
        [ 0.0340245 , -0.04382233, -0.00749094, -0.04192519,
         -0.04241786, -0.03701735, -0.02274007, -0.01853905,
         -0.01521877,  0.03546393],
        [ 0.0340245 , -0.04382233, -0.00749094, -0.04192519,
         -0.04241786, -0.03701735, -0.02274007, -0.01853905,
         -0.01521877,  0.03546393],
        [-0.04680735,  0.01476916, -0.02595383, -0.04941699,
          0.02458652,  0.00723235, -0.04219648, -0.02382298,
          0.01704353, -0.00160163],
        [ 0.01125692,  0.03212735, -0.00209961,  0.04285251,
          0.02022097, -0.02365898,  0.00273307, -0.03673876,
          0.03904477,  0.02370882],
        [ 0.02191875, -0.00577138, -0.03034891, -0.0

In [22]:
embedded_docs[0]

array([   0,    0,    0,    0,  266, 8806, 6268, 2244], dtype=int32)